languageCode = "en"
languageName = "English"
weight = 1
title = "Mrinank Verma"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"


[author]
name = "Mrinank Verma"
image = "img/profile.jpeg"
headline = "Software Architect and Project Manager"
bio = "Certified OSCP Penetration Tester and DevSecOps Professional | Architect of Large-Scale Distributed Systems & Secure Pipelines | Expertise in Malware Analysis Frameworks, SIEM/EDR, Incident Response, and VAPT"
links = [
    { github = "https://github.com/v-mrinank"},
    { instagram = "https://www.instagram.com/mrinankverma/"},
    { linkedin = "https://www.linkedin.com/in/mrinank-verma"}
]
